// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	frontend_auth "gomall/app/frontend/biz/router/frontend/auth"
	frontend_cart "gomall/app/frontend/biz/router/frontend/cart"
	frontend_category "gomall/app/frontend/biz/router/frontend/category"
	frontend_home "gomall/app/frontend/biz/router/frontend/home"
	frontend_product "gomall/app/frontend/biz/router/frontend/product"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	frontend_cart.Register(r)

	frontend_category.Register(r)

	frontend_product.Register(r)

	frontend_auth.Register(r)

	frontend_home.Register(r)
}
